README.md
docs/index.html
docs/json/r6OperatorCounters.json

Fixes #10 
- Operator groups, sides & operations
- Update readme
- Cleanup index.html

Operator teams and operations

---

docs/index.html

Fix GitHub button going to wrong URL

---

package-lock.json
package.json

Upgrade to latest karma version to remove timeSpan dependency

---

src/main/json/r6OperatorCounters.json

https://github.com/BurkusCat/r6-operator-counters/issues/100

Issue #100 - Doc

---

src/main/json/r6OperatorCounters.json

Ying counters Jager - fixes #51
Thatcher counters Clash - fixes #59
IQ hard counters Valk - fixes #60
Zofia counters Castle - fixes #58
Ash & Zofia counters Maestro - fixes #55
Finka counters Caveira - fixes #71
Maverick counters Mira - fixes #70
Hibana counters Mira - fixes #85

Update operator relationships

---

src/main/json/r6OperatorCounters.json

Added a hard counter arrow from ela to montagne

ela hard counters montagne

---

src/main/scripts/neo4jd3.js

Added the method alphaDecay to reduce render time. Pulled from this repo: https://github.com/d3/d3-force#simulation_alphaDecay

Added the method alphaDecay to reduce render time

---

gulp/build.js
gulp/default.js
gulp/styles.js

This reverts commit 6df2d6294ece11c0d41a8aefc433b09cd63441f2.
Just reverting the commit for now. We can take a look at getting the gulp tasks fixed again later, just thought it would be good to get the site back up to speed again!

Revert "gulp bug fixed"

---

src/main/json/r6OperatorCounters.json

This PR adds Vigil hard counter towards Lion and closes issue #135.

Vigil's hard counter added

---

src/main/json/r6OperatorCounters.json

Hello!
This PR addresses #119.
Found you on Up for Grabs. There were several issues that looked fairly easy, so I may try to tackle a few. :)

Added soft counter, Glaz vs. Smoke

---

package-lock.json
src/main/json/r6OperatorCounters.json

Added a brief description of why IQ would be a soft counter to kaid. Solved issue #93.

Added IQ as a soft counter to Kaid. Solved issue #93.

---

src/main/json/r6OperatorCounters.json

Added Dokkaebi as a minor counter to Caveira. Solved issue #94 
ran "npm start" and checked for arrow
"npm test" failed 2 tests, is that.. normal?

Added Dokkaebi as a minor counter to Caveira. Solved issue #94.

---

.jshintrc
gulp/scripts.js
package-lock.json
package.json

Wrote some code in neo4jd3.js with ES6 syntax and it seems to read it fine.
I didn't really change any of the existing code to ES6 syntax though.
Let me know if you need anything else for upgrading to ES6. (Pretty lost direction-wise)

Upgrade To ES6. Solved issue #39.

---

src/main/html/index.html

Correct file casing

---

src/main/create-operator-json/operators/frost.js

Added Frost -> Finka counter, changed 'grappling' to 'rappelling' in Frost -> Amaru counter. In reference to issue #89

Frost Counter Update

---

src/main/create-operator-json/operators/oryx.js
src/main/create-operator-json/operators/warden.js

Added Oryx's hard counter for Montagne and Blitz and Warden's hard counter for Blitz.

Added minor counter changes

---

src/main/html/index.html

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://csp-evaluator.withgoogle.com/

Add content security policy

---

src/main/create-operator-json/operators/wamai.js

Changed "Thathcer" to "Thatcher" in first Wamai Counter

Fixed typo in Wamai.js

---

src/main/create-operator-json/operators/pulse.js

Pulse now hard counters Maverick. This PR implements the change for Pulse.

feat: add pulse hard counter for maverick

---

src/main/create-operator-json/operators/buck.js

Added minor counters to buck when trying to eliminate electrical traps from Bandit or Kaid. as per issue 231 https://github.com/BurkusCat/r6-operator-counters/issues/231

Updated Buck with minor counters

---

package.json

I was struggling to find the exact version of node to use and then I finally found it through trial and error so thought to include engines section for future.

Added engines section

---

src/main/create-operator-json/operators/lesion.js

Updated counters to show the fact that Lesion soft counters Finka.
#80

Updated counters

---

src/main/create-operator-json/operators/ash.js

Thorn's name was in place of Azami in Ash's counters, I just fixed it so it correctly shows the right operator.

Fixed wrong operator name in ash counters.
